### ISSUE TITLE
Limiting product types

### ISSUE THREAD

**Issue by mcoughlin** [usgs/pdl#137]
I am interested in restricting the types of products I ingest to save  space (or perhaps to just exclude shakemap :). In listener_exec, I have includeTypes = origin, internal-origin set, but I suspect this does not limit the product types ingested (just how they are analyzed). Is it possible to restrict the product types to save space?

**Comment by jmfee-usgs** [comment]
Notifications for all products are always processed, but are relatively small.  Only products included by listeners are downloaded.

The indexer is a special case and always downloads origin, associate, disassociate, trump, and trump-origin products, in addition to any other included products, because these are necessary for accurate event association.

If listener_exec is the only configured listener, then only origin and internal-origin should be downloaded.

**Comment by mcoughlin** [comment]
Ok thanks @jmfee-usgs, the indexer is indeed what I was using by accident.
