### ISSUE TITLE
shakemap indexer module shouldn't override PDL properties

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/pdl#2]
This time handling fails when the event time uses "UTC" or anything non-ISO8601-ish:
https://github.com/usgs/pdl/blob/master/src/gov/usgs/earthquake/shakemap/GridXMLHandler.java#L140

Possibly only add properties that are missing, or do not add properties when "enough" already exist.

**Comment by jdbrown-USGS** [comment]
- Talk to Bruce to see if we should be setting these properties at all.
if yes do the rest of this stuff. if no then do nothing.
- Fix the date parsing issue as described above.
- For every property being set in the grid xml handler, Only set property if the property is null.

**Comment by jmfee-usgs** [comment]
Properties currently being summarized:
ELEMENT[ATTRIBUTE] -> PROPERTY


# grid.xml
shakemap_grid[process_timestamp] -> process-timestamp
shakemap_grid[shakemap_version] -> version
shakemap_grid[shakemap_event_type] -> event-type
shakemap_grid[map_status] -> map-status

event[lat] -> latitude
event[lon] -> longitude
event[magnitude] -> magnitude
event[depth] -> depth
event[event_timestamp] -> eventtime
event[event_description] -> event-description

grid_specification[lon_min] -> minimum-longitude
grid_specification[lon_max] -> maximum-longitude
grid_specification[lat_min] -> minimum-latitude
grid_specification[lat_max] -> maximum-latitude

If missing "eventsource" or "eventsourcecode" property
  shakemap_grid[shakemap_originator] -> eventsource
  shakemap_grid[shakemap_id] -> eventsourcecode
(overridden by)
  event[event_network] -> eventsource
  event[event_id] -> eventsourcecode


# info.xml
[tag="mi_max"] -> maxmmi

**Comment by emcwhirter-usgs** [comment]
For each property:
 - if it already has a value
   - compare them and if they differ, log a warning
   - do not set value
 - if it doesn't have a value
   - set the value

**Comment by emartinez-usgs** [comment]
Why was the general approach overhauled? Would it not be sufficient (in the previous source code) to simply check if the given `shakemap` product already had the parsed property and conditionally set the property? That seems like a less-invasive change, though this can work as well.

While many of the specific comments below are minor, there exist one functional problem as well. The property names differ between then XML and the Product. (See the mapping in @jmfee-usgs comment above). So in the `valueIsEmpty` check, the Product will most likely never have a property with the same name as that in the XML, this `valueIsEmpty` will almost always return `true` and the property will be set. A possible refactor might be:
```java
public boolean valueIsEmpty (String xmlValue, String productValue) {
  if (xmlValue == null) {
    return false;
  }
  if (productValue == null) {
    return true;
  }
  if (!productValue.equals(xmlValue)) {
    // Log it
  }

  return false
}
```

And then to call this method you would have to request the appropriately-named properties off the `gridXml` as well as `this.properties`.

Below are some additional minor changes:

GridXMLHandler.java
- XML_NAME variable declared but never used
- XML_VALUE variable declared but never used
- Documentation needs updating
  - The GridXMLHandler no longer sets properties on the ShakeMap product
  - The parse method does not return a ShakeMap anymore, but rather a map of parsed properties

ShakeMap.java
- `valueIsEmpty` method should create a local variable for the result of `getProperties().get(property)` rather than looking it up potentially twice
