### ISSUE TITLE
java.sql.SQLException: columns source, sourceCode are not unique

### ISSUE THREAD

**Issue by vinceq-usgs** [usgs/pdl#42]
Was getting this error in my ProductClient.jar error file starting July 6. As a result, my PDL client was not creating any add/update triggers for DYFI/ShakeMap. (Delete triggers seem to be working.)

Eric recommended deleting entire client SQLite database, which fixed it for now.

**Comment by emartinez-usgs** [comment]
Some background information @jmfee-usgs and I discovered while looking into this...

Looking at the index history, it seems like there were two events relatively nearby in space/time that got chosen as candidate events for association when the new product arrived. One of these events had been deleted while the other had not. The deleted even matched the eventSource + eventSourceCode strong association, but because it was deleted, it was not chosen. The lesser match was chosen for association and that event attempted to update its event (table) source + code values (which were the same as the deleted event) and thus the error occurred.

As a possible workaround, the `chooseEvent` method could ignore deleted products when using the `sameSourceDifferentCode` to prevent associations, but it should include deleted products when using the `sameSourceDifferentCode` to force associations.

https://github.com/usgs/pdl/blob/master/src/gov/usgs/earthquake/indexer/DefaultAssociator.java#L90-L166

There may be other solutions.

**Comment by jmfee-usgs** [comment]
To clarify the background information:

- both events were deleted
- we should continue ignoring deleted products/sub-events when considering the "same source different code" to prevent association, but should consider deleted products for the strong event id association.

The referenced method is probably the best place to fix the problem.

**Comment by jmfee-usgs** [comment]
I believe this is fixed by https://github.com/usgs/pdl/releases/tag/v1.12.1
